### ISSUE TITLE
There is no code

### ISSUE THREAD

**Issue by dyyyl** [ConnorMinielly/videobooth#1]
How can you license software without software?

**Comment by dyyyl** [comment]
bottom text

**Comment by ConnorMinielly** [comment]
Its called being lean and efficient thank you very much. I've taken this project down from 173 lines of code to 0, a 100% reduction. 
Observe:
`console.log('do video stuff')`
became:
`     `

**Comment by ConnorMinielly** [comment]
as of commit #98e73f4078dc5f4068fb253b1c87e0dadb2952da there is now some code.
